export const blogPostsData = [
  {
    title: 'The Future of E-Commerce: Trends Shaping 2025',
    excerpt:
      'Discover the emerging trends that will define online shopping in 2025, from AI-powered personalization to immersive AR experiences.',
    category: 'ecommerce',
    author: 'Sarah Johnson',
    authorRole: 'E-Commerce Strategist',
    publishedDate: new Date('2024-12-15'),
    readTime: 8,
    featured: true,
    tags: [{ tag: 'E-Commerce' }, { tag: 'AI' }, { tag: 'Trends' }, { tag: '2025' }],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'The e-commerce landscape is evolving at an unprecedented pace. As we look ahead to 2025, several transformative trends are reshaping how consumers discover, evaluate, and purchase products online. Understanding these shifts is crucial for businesses that want to stay ahead of the curve.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'AI-Powered Personalization',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Artificial intelligence is revolutionizing how online stores interact with customers. Advanced algorithms now predict customer preferences with stunning accuracy, creating truly personalized shopping experiences. From product recommendations to dynamic pricing, AI is making every interaction feel custom-tailored.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
  },
  {
    title: 'Building Accessible Web Applications: A Complete Guide',
    excerpt:
      'Learn how to create inclusive digital experiences that work for everyone, with practical tips and real-world examples.',
    category: 'development',
    author: 'Alex Chen',
    authorRole: 'Frontend Developer',
    publishedDate: new Date('2024-12-10'),
    readTime: 12,
    featured: false,
    tags: [{ tag: 'Accessibility' }, { tag: 'Web Development' }, { tag: 'Inclusive Design' }],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Web accessibility is not just a nice-to-have feature - it's a fundamental right and legal requirement in many jurisdictions. Building accessible web applications ensures that everyone, regardless of their abilities, can use and enjoy your digital products.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
  },
  {
    title: 'UX Psychology: Understanding How Users Think',
    excerpt:
      'Dive deep into the psychology behind user behavior and learn how to design interfaces that resonate with your audience.',
    category: 'ux-design',
    author: 'Maria Rodriguez',
    authorRole: 'UX Designer',
    publishedDate: new Date('2024-12-05'),
    readTime: 10,
    featured: false,
    tags: [{ tag: 'UX Design' }, { tag: 'Psychology' }, { tag: 'User Behavior' }],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Understanding user psychology is crucial for creating effective digital experiences. By learning how users think, feel, and behave, we can design interfaces that not only look good but also feel intuitive and engaging.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
  },
  {
    title: 'From Zero to Launch: Building a SaaS Product in 90 Days',
    excerpt:
      'A detailed case study of how we helped a startup go from concept to paying customers in just three months.',
    category: 'case-study',
    author: 'David Kim',
    authorRole: 'Product Manager',
    publishedDate: new Date('2024-11-28'),
    readTime: 15,
    featured: true,
    tags: [{ tag: 'SaaS' }, { tag: 'Startup' }, { tag: 'Case Study' }],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Building a successful SaaS product requires more than just technical skills. It demands a deep understanding of your market, a clear vision, and the ability to execute quickly. In this case study, we'll walk through how we helped a startup launch their product in just 90 days.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
  },
  {
    title: 'The Art of Minimalist Design: Less is More',
    excerpt:
      'Explore the principles of minimalist design and how to create beautiful, focused interfaces that users love.',
    category: 'design',
    author: 'Emma Wilson',
    authorRole: 'Designer',
    publishedDate: new Date('2024-11-20'),
    readTime: 7,
    featured: false,
    tags: [{ tag: 'Design' }, { tag: 'Minimalism' }, { tag: 'UI Design' }],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Minimalist design isn't about removing everything - it's about removing everything unnecessary. When done right, minimalist interfaces can be both beautiful and highly functional, guiding users' attention to what matters most.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
  },
  {
    title: 'SEO in 2025: What Actually Works',
    excerpt:
      'Cut through the noise and discover the SEO strategies that will drive real results in 2025.',
    category: 'seo',
    author: 'James Thompson',
    authorRole: 'SEO Specialist',
    publishedDate: new Date('2024-11-15'),
    readTime: 9,
    featured: false,
    tags: [{ tag: 'SEO' }, { tag: 'Marketing' }, { tag: '2025' }],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "SEO is constantly evolving, and what worked last year might not work today. In this comprehensive guide, we'll explore the SEO strategies that are actually driving results in 2025, based on real data and case studies.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
  },
]
