export const servicesData = [
  {
    title: 'Business Coaching',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'One-on-one coaching to help you reach your business goals with personalized strategies and actionable insights.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    shortDescription: '1-on-1 sessions',
    highlighted: true,
    price: 150,
    duration: 'Ongoing',
    features: [
      { feature: '1-on-1 Sessions' },
      { feature: 'Custom Strategy' },
      { feature: 'Ongoing Support' },
    ],
    ctaText: 'Get Started',
    ctaUrl: '/contact',
  },
  {
    title: 'UI Design',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Beautiful, intuitive interfaces that users love. From wireframes to high-fidelity mockups.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    shortDescription: 'Full-stack solutions',
    highlighted: false,
    price: 2500,
    duration: '2-4 weeks',
    features: [
      { feature: 'Wireframes' },
      { feature: 'High-fidelity Mockups' },
      { feature: 'Design System' },
    ],
    ctaText: 'Get Quote',
    ctaUrl: '/contact',
  },
  {
    title: 'UX Design',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Research-backed user experiences that drive engagement and conversions.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    shortDescription: 'Research-backed experiences',
    highlighted: false,
    price: 3000,
    duration: '3-5 weeks',
    features: [
      { feature: 'User Research' },
      { feature: 'User Testing' },
      { feature: 'Conversion Optimization' },
    ],
    ctaText: 'Learn More',
    ctaUrl: '/contact',
  },
  {
    title: 'Marketing',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Data-driven marketing strategies that grow your business and reach the right audience.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    shortDescription: 'Data-driven strategies',
    highlighted: false,
    price: 2000,
    duration: 'Ongoing',
    features: [
      { feature: 'SEO Optimization' },
      { feature: 'Content Strategy' },
      { feature: 'Analytics Setup' },
    ],
    ctaText: 'Get Started',
    ctaUrl: '/contact',
  },
  {
    title: 'Development',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Custom web and mobile applications built with modern technologies.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    shortDescription: 'Custom applications',
    highlighted: false,
    price: 5000,
    duration: '6-12 weeks',
    features: [
      { feature: 'Web Applications' },
      { feature: 'Mobile Apps' },
      { feature: 'API Development' },
    ],
    ctaText: 'Get Quote',
    ctaUrl: '/contact',
  },
  {
    title: 'SEO',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Improve your search rankings and drive organic traffic to your website.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    shortDescription: 'Search optimization',
    highlighted: false,
    price: 1200,
    duration: 'Ongoing',
    features: [
      { feature: 'Keyword Research' },
      { feature: 'Technical SEO' },
      { feature: 'Content Optimization' },
    ],
    ctaText: 'Get Started',
    ctaUrl: '/contact',
  },
]
