export const testimonialsData = [
  {
    name: 'Sarah Chen',
    role: 'Founder at TechStart',
    company: 'TechStart',
    text: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'This template saved us months of development time. The code quality is exceptional and the design is absolutely beautiful.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    rating: 5,
    featured: true,
    order: 1,
    website: 'https://techstart.com',
  },
  {
    name: 'Michael Rodriguez',
    role: 'CEO at Innovate Labs',
    company: 'Innovate Labs',
    text: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Best investment we made. Our conversion rate increased by 40% after switching. The performance is incredible.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    rating: 5,
    featured: true,
    order: 2,
    website: 'https://innovatelabs.com',
  },
  {
    name: 'Emily Thompson',
    role: 'Designer at Studio X',
    company: 'Studio X',
    text: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Finally, a template that doesn't compromise on design. Every detail is thoughtfully crafted.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    rating: 5,
    featured: true,
    order: 3,
    website: 'https://studio-x.com',
  },
  {
    name: 'Alex Johnson',
    role: 'Marketing Director',
    company: 'GrowthCo',
    text: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'The analytics and tracking features are outstanding. We can finally see exactly how our campaigns are performing.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    rating: 5,
    featured: false,
    order: 4,
    website: 'https://growthco.com',
  },
  {
    name: 'Lisa Wang',
    role: 'Product Manager',
    company: 'NextGen',
    text: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'The multi-tenant architecture is exactly what we needed. Our clients love having their own isolated environments.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    rating: 5,
    featured: false,
    order: 5,
    website: 'https://nextgen.com',
  },
]
