/**
 * Active Template Configuration
 * Generated by JUNO CLI
 *
 * This file defines the current active template state for the JUNO system.
 * It serves as the explicit handoff point between the CLI and the Next.js app.
 */

export interface TemplateConfig {
  template: string
  variation: string
  companyName: string
  tagline: string
  features: string[]
  providers: {
    database?: string
    paymentProvider?: string
    authProvider?: string
    cmsProvider?: string
    emailProvider?: string
    analyticsProvider?: string
  }
  metadata: {
    title: string
    description: string
    keywords: string[]
    author: string
  }
  createdAt: string
  updatedAt: string
}

export const ACTIVE_TEMPLATE_CONFIG: TemplateConfig = {
  template: 'default',
  variation: 'complete',
  companyName: 'astro',
  tagline: 'authentic streetwear',
  features: [
    'shop',
    'auth',
    'cms',
    'contact',
    'analytics',
    'i18n',
    'pwa',
    'seo',
    'themes',
    'ab-testing',
  ],
  providers: {
    database: 'sqlite',
    paymentProvider: 'stripe',
    authProvider: 'nextauth',
    cmsProvider: 'payload',
    emailProvider: 'resend',
    analyticsProvider: 'ga4',
  },
  metadata: {
    title: 'astro - authentic streetwear',
    description: 'authentic streetwear',
    keywords: ['default', 'website', 'professional', 'astro'],
    author: 'astro',
  },
  createdAt: '2025-11-03T17:48:29.625Z',
  updatedAt: '2025-11-03T17:48:29.627Z',
}

export function getActiveTemplateConfig(): TemplateConfig {
  return ACTIVE_TEMPLATE_CONFIG
}
